In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import sys

print(sys.executable)  #

/home/nasim/Desktop/work/rag/sec-10k-rag/.venv/bin/python

In [3]:
from sec_10k_rag.split_text.lib import  load_ndjson, drop_short_sections, chunk_sections

In [4]:
import polars as pl
from pathlib import Path

In [5]:
PRJ_ROOT_DIR = Path.cwd().parent
MIN_CHARS = 150
TARGET_CHARS = 500
META_COLUMNS = [
    "section_id",
    "ticker",
    "cik",
    "fiscal_year",
    "item",
    "title",
    "report_date",
    "source_url",
]
DATA_DIR = Path("data/processed")

In [6]:
df = load_ndjson(PRJ_ROOT_DIR / DATA_DIR / "sections.jsonl")

In [7]:
with pl.Config(tbl_cols=-1, fmt_str_lengths=TARGET_CHARS, tbl_rows=-1):
    print(df.filter(pl.col("n_chars") > 80).filter(pl.col("n_chars") < 155).sort(pl.col("n_chars")).select(pl.exclude("text")))

shape: (15, 11)
┌─────────┬────────┬─────────┬────────┬────────┬────────┬────────┬────────┬──────┬────────┬────────┐
│ section ┆ ticker ┆ cik     ┆ fiscal ┆ report ┆ access ┆ source ┆ source ┆ item ┆ title  ┆ n_char │
│ _id     ┆ ---    ┆ ---     ┆ _year  ┆ _date  ┆ ion    ┆ _forma ┆ _url   ┆ ---  ┆ ---    ┆ s      │
│ ---     ┆ str    ┆ str     ┆ ---    ┆ ---    ┆ ---    ┆ t      ┆ ---    ┆ str  ┆ str    ┆ ---    │
│ str     ┆        ┆         ┆ i64    ┆ str    ┆ str    ┆ ---    ┆ str    ┆      ┆        ┆ i64    │
│         ┆        ┆         ┆        ┆        ┆        ┆ str    ┆        ┆      ┆        ┆        │
╞═════════╪════════╪═════════╪════════╪════════╪════════╪════════╪════════╪══════╪════════╪════════╡
│ NVDA-20 ┆ NVDA   ┆ 0001045 ┆ 2026   ┆ 2026-0 ┆ 000104 ┆ html   ┆ https: ┆ 9    ┆ Change ┆ 98     │
│ 26-item ┆        ┆ 810     ┆        ┆ 1-25   ┆ 5810-2 ┆        ┆ //www. ┆      ┆ s in   ┆        │
│ 9       ┆        ┆         ┆        ┆        ┆ 6-0000 ┆        ┆ sec.go ┆      ┆ and    ┆        │
│         ┆        ┆         ┆        ┆        ┆ 21     ┆        ┆ v/Arch ┆      ┆ Disagr ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ ives/e ┆      ┆ eement ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ dgar/d ┆      ┆ s with ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ ata/10 ┆      ┆ Accoun ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 45810/ ┆      ┆ tants  ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 000104 ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 581026 ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 000021 ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ /nvda- ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 202601 ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 25.htm ┆      ┆        ┆        │
│ NVDA-20 ┆ NVDA   ┆ 0001045 ┆ 2025   ┆ 2025-0 ┆ 000104 ┆ html   ┆ https: ┆ 9    ┆ Change ┆ 98     │
│ 25-item ┆        ┆ 810     ┆        ┆ 1-26   ┆ 5810-2 ┆        ┆ //www. ┆      ┆ s in   ┆        │
│ 9       ┆        ┆         ┆        ┆        ┆ 5-0000 ┆        ┆ sec.go ┆      ┆ and    ┆        │
│         ┆        ┆         ┆        ┆        ┆ 23     ┆        ┆ v/Arch ┆      ┆ Disagr ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ ives/e ┆      ┆ eement ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ dgar/d ┆      ┆ s with ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ ata/10 ┆      ┆ Accoun ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 45810/ ┆      ┆ tants  ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 000104 ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 581025 ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 000023 ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ /nvda- ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 202501 ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 26.htm ┆      ┆        ┆        │
│ NVDA-20 ┆ NVDA   ┆ 0001045 ┆ 2024   ┆ 2024-0 ┆ 000104 ┆ html   ┆ https: ┆ 9    ┆ Change ┆ 98     │
│ 24-item ┆        ┆ 810     ┆        ┆ 1-28   ┆ 5810-2 ┆        ┆ //www. ┆      ┆ s in   ┆        │
│ 9       ┆        ┆         ┆        ┆        ┆ 4-0000 ┆        ┆ sec.go ┆      ┆ and    ┆        │
│         ┆        ┆         ┆        ┆        ┆ 29     ┆        ┆ v/Arch ┆      ┆ Disagr ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ ives/e ┆      ┆ eement ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ dgar/d ┆      ┆ s with ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ ata/10 ┆      ┆ Accoun ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 45810/ ┆      ┆ tants  ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 000104 ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 581024 ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 000029 ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ /nvda- ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 202401 ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 28.htm ┆      ┆        ┆        │
│ TSLA-20 ┆ TSLA   ┆ 0001318 ┆ 2025   ┆ 2025-1 ┆ 000162 ┆ html   ┆ https: ┆ 9    ┆ Change ┆ 98     │
│ 25-item ┆        ┆ 605     ┆        ┆ 2-31   ┆ 8280-2 ┆        ┆ //www. ┆      ┆ s in   ┆        │
│ 9       ┆        ┆         ┆        ┆        ┆ 6-0039 ┆        ┆ sec.go ┆      ┆ and    ┆        │
│         ┆        ┆         ┆        ┆        ┆ 52     ┆        ┆ v/Arch ┆      ┆ Disagr ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ ives/e ┆      ┆ eement ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ dgar/d ┆      ┆ s with ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ ata/13 ┆      ┆ Accoun ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 18605/ ┆      ┆ tants  ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 000162 ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 828026 ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 003952 ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ /tsla- ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 202512 ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 31.htm ┆      ┆        ┆        │
│ TSLA-20 ┆ TSLA   ┆ 0001318 ┆ 2024   ┆ 2024-1 ┆ 000162 ┆ html   ┆ https: ┆ 9    ┆ Change ┆ 98     │
│ 24-item ┆        ┆ 605     ┆        ┆ 2-31   ┆ 8280-2 ┆        ┆ //www. ┆      ┆ s in   ┆        │
│ 9       ┆        ┆         ┆        ┆        ┆ 5-0030 ┆        ┆ sec.go ┆      ┆ and    ┆        │
│         ┆        ┆         ┆        ┆        ┆ 63     ┆        ┆ v/Arch ┆      ┆ Disagr ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ ives/e ┆      ┆ eement ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ dgar/d ┆      ┆ s with ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ ata/13 ┆      ┆ Accoun ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 18605/ ┆      ┆ tants  ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 000162 ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 828025 ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 003063 ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ /tsla- ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 202412 ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 31.htm ┆      ┆        ┆        │
│ TSLA-20 ┆ TSLA   ┆ 0001318 ┆ 2023   ┆ 2023-1 ┆ 000162 ┆ html   ┆ https: ┆ 9    ┆ Change ┆ 98     │
│ 23-item ┆        ┆ 605     ┆        ┆ 2-31   ┆ 8280-2 ┆        ┆ //www. ┆      ┆ s in   ┆        │
│ 9       ┆        ┆         ┆        ┆        ┆ 4-0023 ┆        ┆ sec.go ┆      ┆ and    ┆        │
│         ┆        ┆         ┆        ┆        ┆ 90     ┆        ┆ v/Arch ┆      ┆ Disagr ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ ives/e ┆      ┆ eement ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ dgar/d ┆      ┆ s with ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ ata/13 ┆      ┆ Accoun ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 18605/ ┆      ┆ tants  ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 000162 ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 828024 ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 002390 ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ /tsla- ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 202312 ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 31.htm ┆      ┆        ┆        │
│ MSFT-20 ┆ MSFT   ┆ 0000789 ┆ 2026   ┆ 2026-0 ┆ 000119 ┆ html   ┆ https: ┆ 9C   ┆ Disclo ┆ 101    │
│ 26-item ┆        ┆ 019     ┆        ┆ 6-30   ┆ 3125-2 ┆        ┆ //www. ┆      ┆ sure   ┆        │
│ 9C      ┆        ┆         ┆        ┆        ┆ 6-3236 ┆        ┆ sec.go ┆      ┆ Regard ┆        │
│         ┆        ┆         ┆        ┆        ┆ 60     ┆        ┆ v/Arch ┆      ┆ ing    ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ ives/e ┆      ┆ Foreig ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ dgar/d ┆      ┆ n Juri ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ ata/78 ┆      ┆ sdicti ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 9019/0 ┆      ┆ ons    ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 001193 ┆      ┆ that   ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 125263 ┆      ┆ Preven ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 23660/ ┆      ┆ t Insp ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ msft-2 ┆      ┆ ection ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 026063 ┆      ┆ s      ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 0.htm  ┆      ┆        ┆        │
│ MSFT-20 ┆ MSFT   ┆ 0000789 ┆ 2025   ┆ 2025-0 ┆ 000095 ┆ html   ┆ https: ┆ 9C   ┆ Disclo ┆ 101    │
│ 25-item ┆        ┆ 019     ┆        ┆ 6-30   ┆ 0170-2 ┆        ┆ //www. ┆      ┆ sure   ┆        │
│ 9C      ┆        ┆         ┆        ┆        ┆ 5-1002 ┆        ┆ sec.go ┆      ┆ Regard ┆        │
│         ┆        ┆         ┆        ┆        ┆ 35     ┆        ┆ v/Arch ┆      ┆ ing    ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ ives/e ┆      ┆ Foreig ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ dgar/d ┆      ┆ n Juri ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ ata/78 ┆      ┆ sdicti ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 9019/0 ┆      ┆ ons    ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 000950 ┆      ┆ that   ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 170251 ┆      ┆ Preven ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 00235/ ┆      ┆ t Insp ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ msft-2 ┆      ┆ ection ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 025063 ┆      ┆ s      ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 0.htm  ┆      ┆        ┆        │
│ MSFT-20 ┆ MSFT   ┆ 0000789 ┆ 2024   ┆ 2024-0 ┆ 000095 ┆ html   ┆ https: ┆ 9C   ┆ Disclo ┆ 101    │
│ 24-item ┆        ┆ 019     ┆        ┆ 6-30   ┆ 0170-2 ┆        ┆ //www. ┆      ┆ sure   ┆        │
│ 9C      ┆        ┆         ┆        ┆        ┆ 4-0878 ┆        ┆ sec.go ┆      ┆ Regard ┆        │
│         ┆        ┆         ┆        ┆        ┆ 43     ┆        ┆ v/Arch ┆      ┆ ing    ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ ives/e ┆      ┆ Foreig ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ dgar/d ┆      ┆ n Juri ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ ata/78 ┆      ┆ sdicti ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 9019/0 ┆      ┆ ons    ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 000950 ┆      ┆ that   ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 170240 ┆      ┆ Preven ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 87843/ ┆      ┆ t Insp ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ msft-2 ┆      ┆ ection ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 024063 ┆      ┆ s      ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 0.htm  ┆      ┆        ┆        │
│ TSLA-20 ┆ TSLA   ┆ 0001318 ┆ 2025   ┆ 2025-1 ┆ 000162 ┆ html   ┆ https: ┆ 9C   ┆ Disclo ┆ 101    │
│ 25-item ┆        ┆ 605     ┆        ┆ 2-31   ┆ 8280-2 ┆        ┆ //www. ┆      ┆ sure   ┆        │
│ 9C      ┆        ┆         ┆        ┆        ┆ 6-0039 ┆        ┆ sec.go ┆      ┆ Regard ┆        │
│         ┆        ┆         ┆        ┆        ┆ 52     ┆        ┆ v/Arch ┆      ┆ ing    ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ ives/e ┆      ┆ Foreig ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ dgar/d ┆      ┆ n Juri ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ ata/13 ┆      ┆ sdicti ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 18605/ ┆      ┆ ons    ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 000162 ┆      ┆ that   ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 828026 ┆      ┆ Preven ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 003952 ┆      ┆ t Insp ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ /tsla- ┆      ┆ ection ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 202512 ┆      ┆ s      ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 31.htm ┆      ┆        ┆        │
│ TSLA-20 ┆ TSLA   ┆ 0001318 ┆ 2024   ┆ 2024-1 ┆ 000162 ┆ html   ┆ https: ┆ 9C   ┆ Disclo ┆ 101    │
│ 24-item ┆        ┆ 605     ┆        ┆ 2-31   ┆ 8280-2 ┆        ┆ //www. ┆      ┆ sure   ┆        │
│ 9C      ┆        ┆         ┆        ┆        ┆ 5-0030 ┆        ┆ sec.go ┆      ┆ Regard ┆        │
│         ┆        ┆         ┆        ┆        ┆ 63     ┆        ┆ v/Arch ┆      ┆ ing    ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ ives/e ┆      ┆ Foreig ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ dgar/d ┆      ┆ n Juri ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ ata/13 ┆      ┆ sdicti ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 18605/ ┆      ┆ ons    ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 000162 ┆      ┆ that   ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 828025 ┆      ┆ Preven ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 003063 ┆      ┆ t Insp ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ /tsla- ┆      ┆ ection ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 202412 ┆      ┆ s      ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 31.htm ┆      ┆        ┆        │
│ TSLA-20 ┆ TSLA   ┆ 0001318 ┆ 2023   ┆ 2023-1 ┆ 000162 ┆ html   ┆ https: ┆ 9C   ┆ Disclo ┆ 101    │
│ 23-item ┆        ┆ 605     ┆        ┆ 2-31   ┆ 8280-2 ┆        ┆ //www. ┆      ┆ sure   ┆        │
│ 9C      ┆        ┆         ┆        ┆        ┆ 4-0023 ┆        ┆ sec.go ┆      ┆ Regard ┆        │
│         ┆        ┆         ┆        ┆        ┆ 90     ┆        ┆ v/Arch ┆      ┆ ing    ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ ives/e ┆      ┆ Foreig ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ dgar/d ┆      ┆ n Juri ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ ata/13 ┆      ┆ sdicti ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 18605/ ┆      ┆ ons    ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 000162 ┆      ┆ that   ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 828024 ┆      ┆ Preven ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 002390 ┆      ┆ t Insp ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ /tsla- ┆      ┆ ection ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 202312 ┆      ┆ s      ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 31.htm ┆      ┆        ┆        │
│ MSFT-20 ┆ MSFT   ┆ 0000789 ┆ 2026   ┆ 2026-0 ┆ 000119 ┆ html   ┆ https: ┆ 9    ┆ Change ┆ 119    │
│ 26-item ┆        ┆ 019     ┆        ┆ 6-30   ┆ 3125-2 ┆        ┆ //www. ┆      ┆ s in   ┆        │
│ 9       ┆        ┆         ┆        ┆        ┆ 6-3236 ┆        ┆ sec.go ┆      ┆ and    ┆        │
│         ┆        ┆         ┆        ┆        ┆ 60     ┆        ┆ v/Arch ┆      ┆ Disagr ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ ives/e ┆      ┆ eement ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ dgar/d ┆      ┆ s with ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ ata/78 ┆      ┆ Accoun ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 9019/0 ┆      ┆ tants  ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 001193 ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 125263 ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 23660/ ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ msft-2 ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 026063 ┆      ┆        ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 0.htm  ┆      ┆        ┆        │
│ MSFT-20 ┆ MSFT   ┆ 0000789 ┆ 2025   ┆ 2025-0 ┆ 000095 ┆ html   ┆ https: ┆ 9    ┆ Change ┆ 119    │
│ 25-item ┆        ┆ 019     ┆        ┆ 6-30   ┆ 0170-2 ┆        ┆ //www. ┆      ┆ s in   ┆        │
│ 9       ┆        ┆         ┆        ┆        ┆ 5-1002 ┆        ┆ sec.go ┆      ┆ and    ┆        │
│         ┆        ┆         ┆        ┆        ┆ 35     ┆        ┆ v/Arch ┆      ┆ Disagr ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ ives/e ┆      ┆ eement ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ dgar/d ┆      ┆ s with ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ ata/78 ┆      ┆ Accoun ┆        │
│         ┆        ┆         ┆        ┆        ┆        ┆        ┆ 9019/0 ┆      ┆ tants  ┆        │

In [8]:
r1 = drop_short_sections(df, MIN_CHARS)

In [9]:
with pl.Config(tbl_cols=-1, tbl_width_chars=-1, fmt_str_lengths=10): print(r1)

shape: (168, 12)
┌─────────────┬────────┬────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬──────┬─────────────┬─────────┬─────────────┐
│ section_id  ┆ ticker ┆ cik        ┆ fiscal_yea… ┆ report_dat… ┆ accession   ┆ source_for… ┆ source_url  ┆ item ┆ title       ┆ n_chars ┆ text        │
│ ---         ┆ ---    ┆ ---        ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---         ┆ ---  ┆ ---         ┆ ---     ┆ ---         │
│ str         ┆ str    ┆ str        ┆ i64         ┆ str         ┆ str         ┆ str         ┆ str         ┆ str  ┆ str         ┆ i64     ┆ str         │
╞═════════════╪════════╪════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪══════╪═════════════╪═════════╪═════════════╡
│ MSFT-2026-… ┆ MSFT   ┆ 0000789019 ┆ 2026        ┆ 2026-06-30  ┆ 0001193125… ┆ html        ┆ https://ww… ┆ 1    ┆ Business    ┆ 42878   ┆ Item 1      │
│             ┆        ┆            ┆             ┆             ┆             ┆             ┆             ┆      ┆             ┆         ┆ Not…        │
│ MSFT-2026-… ┆ MSFT   ┆ 0000789019 ┆ 2026        ┆ 2026-06-30  ┆ 0001193125… ┆ html        ┆ https://ww… ┆ 1A   ┆ Risk Facto… ┆ 81122   ┆ Item 1A     │
│             ┆        ┆            ┆             ┆             ┆             ┆             ┆             ┆      ┆             ┆         ┆ IT…         │
│ MSFT-2026-… ┆ MSFT   ┆ 0000789019 ┆ 2026        ┆ 2026-06-30  ┆ 0001193125… ┆ html        ┆ https://ww… ┆ 1B   ┆ Unresolved… ┆ 282     ┆ Item 1B, 1… │
│ MSFT-2026-… ┆ MSFT   ┆ 0000789019 ┆ 2026        ┆ 2026-06-30  ┆ 0001193125… ┆ html        ┆ https://ww… ┆ 1C   ┆ Cybersecur… ┆ 8220    ┆ ITEM 1C. C… │
│ MSFT-2026-… ┆ MSFT   ┆ 0000789019 ┆ 2026        ┆ 2026-06-30  ┆ 0001193125… ┆ html        ┆ https://ww… ┆ 2    ┆ Properties  ┆ 1200    ┆ Item 2, 3,… │
│ …           ┆ …      ┆ …          ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           ┆ …    ┆ …           ┆ …       ┆ …           │
│ TSLA-2023-… ┆ TSLA   ┆ 0001318605 ┆ 2023        ┆ 2023-12-31  ┆ 0001628280… ┆ html        ┆ https://ww… ┆ 12   ┆ Security O… ┆ 243     ┆ ITEM 12. S… │
│ TSLA-2023-… ┆ TSLA   ┆ 0001318605 ┆ 2023        ┆ 2023-12-31  ┆ 0001628280… ┆ html        ┆ https://ww… ┆ 13   ┆ Certain Re… ┆ 221     ┆ ITEM 13. C… │
│ TSLA-2023-… ┆ TSLA   ┆ 0001318605 ┆ 2023        ┆ 2023-12-31  ┆ 0001628280… ┆ html        ┆ https://ww… ┆ 14   ┆ Principal … ┆ 195     ┆ ITEM 14. P… │
│ TSLA-2023-… ┆ TSLA   ┆ 0001318605 ┆ 2023        ┆ 2023-12-31  ┆ 0001628280… ┆ html        ┆ https://ww… ┆ 15   ┆ Exhibits a… ┆ 34472   ┆ ITEM 15. E… │
│ TSLA-2023-… ┆ TSLA   ┆ 0001318605 ┆ 2023        ┆ 2023-12-31  ┆ 0001628280… ┆ html        ┆ https://ww… ┆ 16   ┆ Form 10-K … ┆ 1288    ┆ ITEM 16. S… │
└─────────────┴────────┴────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴──────┴─────────────┴─────────┴─────────────┘

In [10]:
r2 = chunk_sections(r1, target_chars=TARGET_CHARS, meta_columns=META_COLUMNS)

In [11]:
with pl.Config(fmt_str_lengths=20, tbl_rows=-1, tbl_cols=-1, tbl_width_chars=-1): 
    display(r2.head(10))

shape: (10, 10)
┌─────────────┬───────────────────────┬─────────────────┬────────┬────────────┬─────────────┬──────┬──────────┬─────────────┬───────────────────────┐
│ chunk_index ┆ text                  ┆ section_id      ┆ ticker ┆ cik        ┆ fiscal_year ┆ item ┆ title    ┆ report_date ┆ source_url            │
│ ---         ┆ ---                   ┆ ---             ┆ ---    ┆ ---        ┆ ---         ┆ ---  ┆ ---      ┆ ---         ┆ ---                   │
│ i64         ┆ str                   ┆ str             ┆ str    ┆ str        ┆ i64         ┆ str  ┆ str      ┆ str         ┆ str                   │
╞═════════════╪═══════════════════════╪═════════════════╪════════╪════════════╪═════════════╪══════╪══════════╪═════════════╪═══════════════════════╡
│ 0           ┆ Item 1                ┆ MSFT-2026-item1 ┆ MSFT   ┆ 0000789019 ┆ 2026        ┆ 1    ┆ Business ┆ 2026-06-30  ┆ https://www.sec.gov/… │
│             ┆ Note About Fo…        ┆                 ┆        ┆            ┆             ┆      ┆          ┆             ┆                       │
│ 1           ┆ PART I                ┆ MSFT-2026-item1 ┆ MSFT   ┆ 0000789019 ┆ 2026        ┆ 1    ┆ Business ┆ 2026-06-30  ┆ https://www.sec.gov/… │
│             ┆ ITEM 1. BUSIN…        ┆                 ┆        ┆            ┆             ┆      ┆          ┆             ┆                       │
│ 2           ┆ We develop and suppo… ┆ MSFT-2026-item1 ┆ MSFT   ┆ 0000789019 ┆ 2026        ┆ 1    ┆ Business ┆ 2026-06-30  ┆ https://www.sec.gov/… │
│ 3           ┆ We believe AI should… ┆ MSFT-2026-item1 ┆ MSFT   ┆ 0000789019 ┆ 2026        ┆ 1    ┆ Business ┆ 2026-06-30  ┆ https://www.sec.gov/… │
│ 4           ┆ We offer an array of… ┆ MSFT-2026-item1 ┆ MSFT   ┆ 0000789019 ┆ 2026        ┆ 1    ┆ Business ┆ 2026-06-30  ┆ https://www.sec.gov/… │
│ 5           ┆ Digital transformati… ┆ MSFT-2026-item1 ┆ MSFT   ┆ 0000789019 ┆ 2026        ┆ 1    ┆ Business ┆ 2026-06-30  ┆ https://www.sec.gov/… │
│ 6           ┆ We prioritize securi… ┆ MSFT-2026-item1 ┆ MSFT   ┆ 0000789019 ┆ 2026        ┆ 1    ┆ Business ┆ 2026-06-30  ┆ https://www.sec.gov/… │
│ 7           ┆ •Build the intellige… ┆ MSFT-2026-item1 ┆ MSFT   ┆ 0000789019 ┆ 2026        ┆ 1    ┆ Business ┆ 2026-06-30  ┆ https://www.sec.gov/… │
│ 8           ┆ •Tackling security f… ┆ MSFT-2026-item1 ┆ MSFT   ┆ 0000789019 ┆ 2026        ┆ 1    ┆ Business ┆ 2026-06-30  ┆ https://www.sec.gov/… │
│ 9           ┆ •Applying AI and amb… ┆ MSFT-2026-item1 ┆ MSFT   ┆ 0000789019 ┆ 2026        ┆ 1    ┆ Business ┆ 2026-06-30  ┆ https://www.sec.gov/… │
└─────────────┴───────────────────────┴─────────────────┴────────┴────────────┴─────────────┴──────┴──────────┴─────────────┴───────────────────────┘

In [12]:
display(r2.head(10))

shape: (10, 10)
┌─────────────┬─────────────┬─────────────┬────────┬───┬──────┬──────────┬────────────┬────────────┐
│ chunk_index ┆ text        ┆ section_id  ┆ ticker ┆ … ┆ item ┆ title    ┆ report_dat ┆ source_url │
│ ---         ┆ ---         ┆ ---         ┆ ---    ┆   ┆ ---  ┆ ---      ┆ e          ┆ ---        │
│ i64         ┆ str         ┆ str         ┆ str    ┆   ┆ str  ┆ str      ┆ ---        ┆ str        │
│             ┆             ┆             ┆        ┆   ┆      ┆          ┆ str        ┆            │
╞═════════════╪═════════════╪═════════════╪════════╪═══╪══════╪══════════╪════════════╪════════════╡
│ 0           ┆ Item 1      ┆ MSFT-2026-i ┆ MSFT   ┆ … ┆ 1    ┆ Business ┆ 2026-06-30 ┆ https://ww │
│             ┆ Note About  ┆ tem1        ┆        ┆   ┆      ┆          ┆            ┆ w.sec.gov/ │
│             ┆ Forward-Loo ┆             ┆        ┆   ┆      ┆          ┆            ┆ Archives/e │
│             ┆ k…          ┆             ┆        ┆   ┆      ┆          ┆            ┆ …          │
│ 1           ┆ PART I      ┆ MSFT-2026-i ┆ MSFT   ┆ … ┆ 1    ┆ Business ┆ 2026-06-30 ┆ https://ww │
│             ┆ ITEM 1.     ┆ tem1        ┆        ┆   ┆      ┆          ┆            ┆ w.sec.gov/ │
│             ┆ BUSINESS    ┆             ┆        ┆   ┆      ┆          ┆            ┆ Archives/e │
│             ┆ GENERA…     ┆             ┆        ┆   ┆      ┆          ┆            ┆ …          │
│ 2           ┆ We develop  ┆ MSFT-2026-i ┆ MSFT   ┆ … ┆ 1    ┆ Business ┆ 2026-06-30 ┆ https://ww │
│             ┆ and support ┆ tem1        ┆        ┆   ┆      ┆          ┆            ┆ w.sec.gov/ │
│             ┆ a broad…    ┆             ┆        ┆   ┆      ┆          ┆            ┆ Archives/e │
│             ┆             ┆             ┆        ┆   ┆      ┆          ┆            ┆ …          │
│ 3           ┆ We believe  ┆ MSFT-2026-i ┆ MSFT   ┆ … ┆ 1    ┆ Business ┆ 2026-06-30 ┆ https://ww │
│             ┆ AI should   ┆ tem1        ┆        ┆   ┆      ┆          ┆            ┆ w.sec.gov/ │
│             ┆ be as emp…  ┆             ┆        ┆   ┆      ┆          ┆            ┆ Archives/e │
│             ┆             ┆             ┆        ┆   ┆      ┆          ┆            ┆ …          │
│ 4           ┆ We offer an ┆ MSFT-2026-i ┆ MSFT   ┆ … ┆ 1    ┆ Business ┆ 2026-06-30 ┆ https://ww │
│             ┆ array of    ┆ tem1        ┆        ┆   ┆      ┆          ┆            ┆ w.sec.gov/ │
│             ┆ services,…  ┆             ┆        ┆   ┆      ┆          ┆            ┆ Archives/e │
│             ┆             ┆             ┆        ┆   ┆      ┆          ┆            ┆ …          │
│ 5           ┆ Digital tra ┆ MSFT-2026-i ┆ MSFT   ┆ … ┆ 1    ┆ Business ┆ 2026-06-30 ┆ https://ww │
│             ┆ nsformation ┆ tem1        ┆        ┆   ┆      ┆          ┆            ┆ w.sec.gov/ │
│             ┆ and ado…    ┆             ┆        ┆   ┆      ┆          ┆            ┆ Archives/e │
│             ┆             ┆             ┆        ┆   ┆      ┆          ┆            ┆ …          │
│ 6           ┆ We          ┆ MSFT-2026-i ┆ MSFT   ┆ … ┆ 1    ┆ Business ┆ 2026-06-30 ┆ https://ww │
│             ┆ prioritize  ┆ tem1        ┆        ┆   ┆      ┆          ┆            ┆ w.sec.gov/ │
│             ┆ security    ┆             ┆        ┆   ┆      ┆          ┆            ┆ Archives/e │
│             ┆ above a…    ┆             ┆        ┆   ┆      ┆          ┆            ┆ …          │
│ 7           ┆ •Build the  ┆ MSFT-2026-i ┆ MSFT   ┆ … ┆ 1    ┆ Business ┆ 2026-06-30 ┆ https://ww │
│             ┆ intelligent ┆ tem1        ┆        ┆   ┆      ┆          ┆            ┆ w.sec.gov/ │
│             ┆ cloud a…    ┆             ┆        ┆   ┆      ┆          ┆            ┆ Archives/e │
│             ┆             ┆             ┆        ┆   ┆      ┆          ┆            ┆ …          │
│ 8           ┆ •Tackling   ┆ MSFT-2026-i ┆ MSFT   ┆ … ┆ 1    ┆ Business ┆ 2026-06-30 ┆ https://ww │
│             ┆ security    ┆ tem1        ┆        ┆   ┆      ┆          ┆            ┆ w.sec.gov/ │
│             ┆ from all    ┆             ┆        ┆   ┆      ┆          ┆            ┆ Archives/e │
│             ┆ an…         ┆             ┆        ┆   ┆      ┆          ┆            ┆ …          │
│ 9           ┆ •Applying   ┆ MSFT-2026-i ┆ MSFT   ┆ … ┆ 1    ┆ Business ┆ 2026-06-30 ┆ https://ww │
│             ┆ AI and      ┆ tem1        ┆        ┆   ┆      ┆          ┆            ┆ w.sec.gov/ │
│             ┆ ambient     ┆             ┆        ┆   ┆      ┆          ┆            ┆ Archives/e │
│             ┆ intel…      ┆             ┆        ┆   ┆      ┆          ┆            ┆ …          │
└─────────────┴─────────────┴─────────────┴────────┴───┴──────┴──────────┴────────────┴────────────┘

In [17]:
def preview_chunks(chunks: pl.DataFrame, n: int = 150) -> pl.DataFrame:
    is_long = pl.col("text").str.len_chars() > n
    return (
        chunks.sort("section_id", "chunk_index")
        .with_columns(
            pl.when(is_long).then(pl.col("text").str.slice(0, n) + "...").otherwise(pl.col("text")).alias(f"first_{n}"),
            pl.when(is_long).then("..." + pl.col("text").str.slice(-n)).otherwise(pl.col("text")).alias(f"last_{n}"),
        )
        .select("section_id", "ticker", f"first_{n}", f"last_{n}", "text", "chunk_index")
    )

In [18]:
report2 = preview_chunks(r2, 50)

In [19]:
with pl.Config(fmt_str_lengths=60, tbl_rows=20, tbl_cols=-1, tbl_width_chars=-1):
    display(report2.slice(270, 40))

shape: (40, 6)
┌─────────────────┬────────┬───────────────────────────────────────────────────────┬───────────────────────────────────────────────────────┬───────────────────────────────────────────────────────────────┬─────────────┐
│ section_id      ┆ ticker ┆ first_50                                              ┆ last_50                                               ┆ text                                                          ┆ chunk_index │
│ ---             ┆ ---    ┆ ---                                                   ┆ ---                                                   ┆ ---                                                           ┆ ---         │
│ str             ┆ str    ┆ str                                                   ┆ str                                                   ┆ str                                                           ┆ i64         │
╞═════════════════╪════════╪═══════════════════════════════════════════════════════╪═══════════════════════════════════════════════════════╪═══════════════════════════════════════════════════════════════╪═════════════╡
│ MSFT-2024-item7 ┆ MSFT   ┆ LinkedIn revenue growth                               ┆ ...s”); and Nuance and GitHub                         ┆ LinkedIn revenue growth                                       ┆ 22          │
│                 ┆        ┆ Revenue from LinkedIn, inc...                         ┆ More Personal Computing                               ┆ Revenue from LinkedIn, including Tal…                         ┆             │
│ MSFT-2024-item7 ┆ MSFT   ┆ Metrics related to our More Personal Computing seg... ┆ ... and non-Pro licenses sold through the OEM channel ┆ Metrics related to our More Personal Computing segment asses… ┆ 23          │
│ MSFT-2024-item7 ┆ MSFT   ┆ Windows Commercial products and cloud services rev... ┆ ...ird-party disc royalties; and other cloud services ┆ Windows Commercial products and cloud services revenue growt… ┆ 24          │
│ MSFT-2024-item7 ┆ MSFT   ┆ Search and news advertising revenue (ex TAC) growt... ┆ ...xcept percentages and per share amounts)           ┆ Search and news advertising revenue (ex TAC) growth           ┆ 25          │
│                 ┆        ┆                                                       ┆ 2024                                                  ┆ Revenue …                                                     ┆             │
│                 ┆        ┆                                                       ┆ 2023                                                  ┆                                                               ┆             │
│ MSFT-2024-item7 ┆ MSFT   ┆ Percentage                                            ┆ ...ccordance with GAAP to non-GAAP financial results. ┆ Percentage                                                    ┆ 26          │
│                 ┆        ┆ Change                                                ┆                                                       ┆ Change                                                        ┆             │
│                 ┆        ┆ Revenue                                               ┆                                                       ┆ Revenue                                                       ┆             │
│                 ┆        ┆ $                                                     ┆                                                       ┆ $                                                             ┆             │
│                 ┆        ┆ 245,122                                               ┆                                                       ┆ 245,122                                                       ┆             │
│                 ┆        ┆ $                                                     ┆                                                       ┆ $                                                             ┆             │
│                 ┆        ┆ 211,915                                               ┆                                                       ┆ 211,915                                                       ┆             │
│                 ┆        ┆ 16%                                                   ┆                                                       ┆ 16%                                                           ┆             │
│                 ┆        ┆ ...                                                   ┆                                                       ┆ Gross marg…                                                   ┆             │
│ MSFT-2024-item7 ┆ MSFT   ┆ Fiscal Year 2024 Compared with Fiscal Year 2023       ┆ ... 17% driven by growth across each of our segments. ┆ Fiscal Year 2024 Compared with Fiscal Year 2023               ┆ 27          │
│                 ┆        ┆ Re...                                                 ┆                                                       ┆ Revenue incr…                                                 ┆             │
│ MSFT-2024-item7 ┆ MSFT   ┆ •Gross margin percentage increased slightly. Exclu... ┆ ...cture, offset in part by sales mix shift to Azure. ┆ •Gross margin percentage increased slightly. Excluding the i… ┆ 28          │
│ MSFT-2024-item7 ┆ MSFT   ┆ Operating expenses increased $4.0 billion or 7% dr... ┆ ....2 billion, $946 million, and $0.13, respectively. ┆ Operating expenses increased $4.0 billion or 7% driven by Ga… ┆ 29          │
│ MSFT-2024-item7 ┆ MSFT   ┆ PART II                                               ┆ ...erating Income                                     ┆ PART II                                                       ┆ 30          │
│                 ┆        ┆ Item 7                                                ┆ Productivity and Business Processes                   ┆ Item 7                                                        ┆             │
│                 ┆        ┆ SEGMENT RESULTS OF OPERATIONS                         ┆                                                       ┆ SEGMENT RESULTS OF OPERATIONS                                 ┆             │
│                 ┆        ┆ (In m...                                              ┆                                                       ┆ (In millions, e…                                              ┆             │
│ MSFT-2024-item7 ┆ MSFT   ┆ $                                                     ┆ ...en by continued customer shift to cloud offerings. ┆ $                                                             ┆ 31          │
│                 ┆        ┆ 40,540                                                ┆                                                       ┆ 40,540                                                        ┆             │
│                 ┆        ┆ $                                                     ┆                                                       ┆ $                                                             ┆             │
│                 ┆        ┆ 34,189                                                ┆                                                       ┆ 34,189                                                        ┆             │
│                 ┆        ┆ 19%                                                   ┆                                                       ┆ 19%                                                           ┆             │
│                 ┆        ┆ Intelligent Cloud                                     ┆                                                       ┆ Intelligent Cloud                                             ┆             │
│                 ┆        ┆ 49,584                                                ┆                                                       ┆ 49,584                                                        ┆             │
│                 ┆        ┆ 37,...                                                ┆                                                       ┆ 37,884                                                        ┆             │
│                 ┆        ┆                                                       ┆                                                       ┆ 31%                                                           ┆             │
│                 ┆        ┆                                                       ┆                                                       ┆ Mo…                                                           ┆             │
│ …               ┆ …      ┆ …                                                     ┆ …                                                     ┆ …                                                             ┆ …           │
│ MSFT-2024-item7 ┆ MSFT   ┆ Severance, hardware-related impairment, and lease ... ┆ ...re (non-GAAP)                                      ┆ Severance, hardware-related impairment, and lease consolidat… ┆ 52          │
│                 ┆        ┆                                                       ┆ $                                                     ┆                                                               ┆             │
│                 ┆        ┆                                                       ┆ 11.80                                                 ┆                                                               ┆             │
│                 ┆        ┆                                                       ┆ $                                                     ┆                                                               ┆             │
│                 ┆        ┆                                                       ┆ 9.81                                                  ┆                                                               ┆             │
│                 ┆        ┆                                                       ┆ 20%                                                   ┆                                                               ┆             │
│                 ┆        ┆                                                       ┆ * Not meaningful.                                     ┆                                                               ┆             │
│ MSFT-2024-item7 ┆ MSFT   ┆ LIQUIDITY AND CAPITAL RESOURCES                       ┆ ... months and thereafter for the foreseeable future. ┆ LIQUIDITY AND CAPITAL RESOURCES                               ┆ 53          │
│                 ┆        ┆ We expect existing...                                 ┆                                                       ┆ We expect existing cash, cas…                                 ┆             │
│ MSFT-2024-item7 ┆ MSFT   ┆ Cash, Cash Equivalents, and Investments               ┆ ...y liquid investment-grade fixed-income securities. ┆ Cash, Cash Equivalents, and Investments                       ┆ 54          │
│                 ┆        ┆ Cash, cash...                                         ┆                                                       ┆ Cash, cash equivalen…                                         ┆             │
│ MSFT-2024-item7 ┆ MSFT   ┆ Valuation                                             ┆ ...inputs are an immaterial portion of our portfolio. ┆ Valuation                                                     ┆ 55          │
│                 ┆        ┆ In general, and where applicable, we use...           ┆                                                       ┆ In general, and where applicable, we use quoted pr…           ┆             │
│ MSFT-2024-item7 ┆ MSFT   ┆ PART II                                               ┆ ...pendent recalculation of prices where appropriate. ┆ PART II                                                       ┆ 56          │
│                 ┆        ┆ Item 7                                                ┆                                                       ┆ Item 7                                                        ┆             │
│                 ┆        ┆ A majority of our investments are p...                ┆                                                       ┆ A majority of our investments are priced by p…                ┆             │
│ MSFT-2024-item7 ┆ MSFT   ┆ Cash Flows                                            ┆ ...n increase in additions to property and equipment. ┆ Cash Flows                                                    ┆ 57          │
│                 ┆        ┆ Cash from operations increased $31.0 bi...            ┆                                                       ┆ Cash from operations increased $31.0 billion to $…            ┆             │
│ MSFT-2024-item7 ┆ MSFT   ┆ Debt Proceeds                                         ┆ ... Item 8 of this Form 10-K) for further discussion. ┆ Debt Proceeds                                                 ┆ 58          │
│                 ┆        ┆ We issue debt to take advantage of f...               ┆                                                       ┆ We issue debt to take advantage of favorable p…               ┆             │
│ MSFT-2024-item7 ┆ MSFT   ┆ Unearned Revenue                                      ┆ ... Item 8 of this Form 10-K) for further discussion. ┆ Unearned Revenue                                              ┆ 59          │
│                 ┆        ┆ Unearned revenue comprises mainly...                  ┆                                                       ┆ Unearned revenue comprises mainly unearned …                  ┆             │
│ MSFT-2024-item7 ┆ MSFT   ┆ The following table outlines the expected future r... ┆ ... Item 8 of this Form 10-K) for further discussion. ┆ The following table outlines the expected future recognition… ┆ 60          │
│ MSFT-2024-item7 ┆ MSFT   ┆ PART II                                               ┆ ...ents and Other Obligations                         ┆ PART II                                                       ┆ 61          │
│                 ┆        ┆ Item 7                                                ┆ Contractual Obligations                               ┆ Item 7                                                        ┆             │
│                 ┆        ┆ Material Cash Requirements and Othe...                ┆                                                       ┆ Material Cash Requirements and Other Obligati…                ┆             │
└─────────────────┴────────┴───────────────────────────────────────────────────────┴───────────────────────────────────────────────────────┴───────────────────────────────────────────────────────────────┴─────────────┘

In [20]:
with pl.Config(fmt_str_lengths=60, tbl_rows=10, tbl_cols=-1, tbl_width_chars=-1):
    display(report2.head(10))

shape: (10, 6)
┌─────────────────┬────────┬───────────────────────────────────────────────────────┬───────────────────────────────────────────────────────┬───────────────────────────────────────────────────────────────┬─────────────┐
│ section_id      ┆ ticker ┆ first_50                                              ┆ last_50                                               ┆ text                                                          ┆ chunk_index │
│ ---             ┆ ---    ┆ ---                                                   ┆ ---                                                   ┆ ---                                                           ┆ ---         │
│ str             ┆ str    ┆ str                                                   ┆ str                                                   ┆ str                                                           ┆ i64         │
╞═════════════════╪════════╪═══════════════════════════════════════════════════════╪═══════════════════════════════════════════════════════╪═══════════════════════════════════════════════════════════════╪═════════════╡
│ MSFT-2024-item1 ┆ MSFT   ┆ Item 1                                                ┆ ...e of new information, future events, or otherwise. ┆ Item 1                                                        ┆ 0           │
│                 ┆        ┆ Note About Forward-Looking Statements                 ┆                                                       ┆ Note About Forward-Looking Statements                         ┆             │
│                 ┆        ┆ This ...                                              ┆                                                       ┆ This report inc…                                              ┆             │
│ MSFT-2024-item1 ┆ MSFT   ┆ PART I                                                ┆ ...wth, and impact in every country around the world. ┆ PART I                                                        ┆ 1           │
│                 ┆        ┆ ITEM 1. BUSINESS                                      ┆                                                       ┆ ITEM 1. BUSINESS                                              ┆             │
│                 ┆        ┆ GENERAL                                               ┆                                                       ┆ GENERAL                                                       ┆             │
│                 ┆        ┆ Embracing Our Futu...                                 ┆                                                       ┆ Embracing Our Future                                          ┆             │
│                 ┆        ┆                                                       ┆                                                       ┆ Microso…                                                      ┆             │
│ MSFT-2024-item1 ┆ MSFT   ┆ We have entered a new age of AI that will fundamen... ┆ ...lock for every country, community, and individual. ┆ We have entered a new age of AI that will fundamentally tran… ┆ 2           │
│ MSFT-2024-item1 ┆ MSFT   ┆ We believe AI should be as empowering across commu... ┆ ...nd built with safety and security from the outset. ┆ We believe AI should be as empowering across communities as … ┆ 3           │
│ MSFT-2024-item1 ┆ MSFT   ┆ What We Offer                                         ┆ ... relevant online advertising to a global audience. ┆ What We Offer                                                 ┆ 4           │
│                 ┆        ┆ Founded in 1975, we develop and supp...               ┆                                                       ┆ Founded in 1975, we develop and support softwa…               ┆             │
│ MSFT-2024-item1 ┆ MSFT   ┆ Our products include operating systems, cross-devi... ┆ ...ther intelligent devices, and related accessories. ┆ Our products include operating systems, cross-device product… ┆ 5           │
│ MSFT-2024-item1 ┆ MSFT   ┆ PART I                                                ┆ ...in the ways the world works, learns, and connects. ┆ PART I                                                        ┆ 6           │
│                 ┆        ┆ Item 1                                                ┆                                                       ┆ Item 1                                                        ┆             │
│                 ┆        ┆ The Ambitions That Drive Us                           ┆                                                       ┆ The Ambitions That Drive Us                                   ┆             │
│                 ┆        ┆ To achie...                                           ┆                                                       ┆ To achieve our vis…                                           ┆             │
│ MSFT-2024-item1 ┆ MSFT   ┆ Our growth depends on securely delivering continuo... ┆ ...ons, knowledge, learning, resources, and insights. ┆ Our growth depends on securely delivering continuous innovat… ┆ 7           │
│ MSFT-2024-item1 ┆ MSFT   ┆ Together, the Microsoft Cloud, Dynamics 365, Micro... ┆ ... professionals learn, sell, market, and get hired. ┆ Together, the Microsoft Cloud, Dynamics 365, Microsoft Teams… ┆ 8           │
│ MSFT-2024-item1 ┆ MSFT   ┆ Build the Intelligent Cloud and Intelligent Edge P... ┆ ...d computing and AI infrastructure and datacenters. ┆ Build the Intelligent Cloud and Intelligent Edge Platform     ┆ 9           │
│                 ┆        ┆                                                       ┆                                                       ┆ Di…                                                           ┆             │
└─────────────────┴────────┴───────────────────────────────────────────────────────┴───────────────────────────────────────────────────────┴───────────────────────────────────────────────────────────────┴─────────────┘