In [9]:
%load_ext autoreload
%autoreload 2
%config Completer.use_jedi = False
import sys

print(sys.executable)  #
from pprint import pprint
import polars as pl
from pathlib import Path

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
/home/nasim/Desktop/work/rag/sec-10k-rag/.venv/bin/python

In [10]:
from groq import Groq

In [11]:
from sec_10k_rag.common.common import write_to_parquet_file, load_parquet

In [ ]:
from sec_10k_rag.step_07_search_quality.config import get_config, ConfigType, get_llm_api_key, ROOT_DIR

In [37]:
from sec_10k_rag.step_07_search_quality.lib import generate_questions, load_chunks_text_from_db, sample_chunks, get_question_vectors, find_nearest_neighbors

In [14]:
print(dir(ConfigType))

['GENERATE_QUESTIONS', 'SCORE_SEARCH', '__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__members__', '__mod__', '__module__', '__mul__', '__name__', '__ne__', '__new__', '__qualname__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'removeprefix', 'removesuffix', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']

In [15]:
config = get_config(ConfigType.GENERATE_QUESTIONS)

In [16]:
print(config)

Config(command='run', root_dir=PosixPath('/home/nasim/Desktop/work/rag/sec-10k-rag'), input_data_dir=PosixPath('/home/nasim/Desktop/work/rag/sec-10k-rag/data/processed/search_quality'), processed_data_dir=PosixPath('/home/nasim/Desktop/work/rag/sec-10k-rag/data/processed/search_quality'), log_dir=PosixPath('/home/nasim/Desktop/work/rag/sec-10k-rag/logs'), temp_dir=PosixPath('/home/nasim/Desktop/work/rag/sec-10k-rag/temp'), instructions=GenerateQuestionsInstructions(db=DbConnInfo(port='5432', dbname='sec10k', user='rag', host='127.0.0.1'), llm_info=LlmInfo(model_name='openai/gpt-oss-120b', temperature=0.0), sample_size=50, seed=42, output_file_name='questions.parquet', chunks_table='chunks', company_names={'MSFT': 'Microsoft', 'NVDA': 'Nvidia', 'TSLA': 'Tesla'}))

In [17]:
instructions = config.instructions

In [18]:
chunks_df = load_chunks_text_from_db(instructions.db, instructions.chunks_table)

In [19]:
display(chunks_df.head(10))

shape: (10, 7)
┌─────────────────┬─────────────┬────────┬─────────────┬──────┬──────────┬─────────────────────────┐
│ section_id      ┆ chunk_index ┆ ticker ┆ fiscal_year ┆ item ┆ title    ┆ text                    │
│ ---             ┆ ---         ┆ ---    ┆ ---         ┆ ---  ┆ ---      ┆ ---                     │
│ str             ┆ i64         ┆ str    ┆ i64         ┆ str  ┆ str      ┆ str                     │
╞═════════════════╪═════════════╪════════╪═════════════╪══════╪══════════╪═════════════════════════╡
│ MSFT-2024-item1 ┆ 0           ┆ MSFT   ┆ 2024        ┆ 1    ┆ Business ┆ Item 1                  │
│                 ┆             ┆        ┆             ┆      ┆          ┆ Note About              │
│                 ┆             ┆        ┆             ┆      ┆          ┆ Forward-Look…           │
│ MSFT-2024-item1 ┆ 1           ┆ MSFT   ┆ 2024        ┆ 1    ┆ Business ┆ PART I                  │
│                 ┆             ┆        ┆             ┆      ┆          ┆ ITEM 1. BUSINESS        │
│                 ┆             ┆        ┆             ┆      ┆          ┆ GENERA…                 │
│ MSFT-2024-item1 ┆ 2           ┆ MSFT   ┆ 2024        ┆ 1    ┆ Business ┆ We have entered a new   │
│                 ┆             ┆        ┆             ┆      ┆          ┆ age of A…               │
│ MSFT-2024-item1 ┆ 3           ┆ MSFT   ┆ 2024        ┆ 1    ┆ Business ┆ What We Offer           │
│                 ┆             ┆        ┆             ┆      ┆          ┆ Founded in 1975,…       │
│ MSFT-2024-item1 ┆ 4           ┆ MSFT   ┆ 2024        ┆ 1    ┆ Business ┆ PART I                  │
│                 ┆             ┆        ┆             ┆      ┆          ┆ Item 1                  │
│                 ┆             ┆        ┆             ┆      ┆          ┆ The Ambitions Th…       │
│ MSFT-2024-item1 ┆ 5           ┆ MSFT   ┆ 2024        ┆ 1    ┆ Business ┆ Together, the Microsoft │
│                 ┆             ┆        ┆             ┆      ┆          ┆ Cloud,…                 │
│ MSFT-2024-item1 ┆ 6           ┆ MSFT   ┆ 2024        ┆ 1    ┆ Business ┆ Build the Intelligent   │
│                 ┆             ┆        ┆             ┆      ┆          ┆ Cloud an…               │
│ MSFT-2024-item1 ┆ 7           ┆ MSFT   ┆ 2024        ┆ 1    ┆ Business ┆ Our cloud business      │
│                 ┆             ┆        ┆             ┆      ┆          ┆ benefits fr…            │
│ MSFT-2024-item1 ┆ 8           ┆ MSFT   ┆ 2024        ┆ 1    ┆ Business ┆ PART I                  │
│                 ┆             ┆        ┆             ┆      ┆          ┆ Item 1                  │
│                 ┆             ┆        ┆             ┆      ┆          ┆ Our AI platform,…       │
│ MSFT-2024-item1 ┆ 9           ┆ MSFT   ┆ 2024        ┆ 1    ┆ Business ┆ GitHub Copilot is at    │
│                 ┆             ┆        ┆             ┆      ┆          ┆ the foref…              │
└─────────────────┴─────────────┴────────┴─────────────┴──────┴──────────┴─────────────────────────┘

In [20]:
sample_df = sample_chunks(chunks_df, n=instructions.sample_size, seed=instructions.seed)

In [21]:
print(sample_df.height)

50

In [22]:
print(chunks_df.height)

2977

In [ ]:
pprint(sorted(m.id for m in Groq(api_key=get_llm_api_key()).models.list().data))

['allam-2-7b',
 'canopylabs/orpheus-arabic-saudi',
 'canopylabs/orpheus-v1-english',
 'meta-llama/llama-prompt-guard-2-22m',
 'meta-llama/llama-prompt-guard-2-86m',
 'openai/gpt-oss-120b',
 'openai/gpt-oss-20b',
 'openai/gpt-oss-safeguard-20b',
 'qwen/qwen3.8-27b',
 'whisper-large-v3',
 'whisper-large-v3-turbo']

In [104]:
questions = generate_questions(
    sample=sample_df,
    llm_info=instructions.llm_info,
    company_names=instructions.company_names
)

In [105]:
display(questions)

shape: (44, 8)
┌─────────────┬─────────────┬────────┬─────────────┬──────┬─────────────┬─────────────┬────────────┐
│ section_id  ┆ chunk_index ┆ ticker ┆ fiscal_year ┆ item ┆ question    ┆ answer      ┆ quote      │
│ ---         ┆ ---         ┆ ---    ┆ ---         ┆ ---  ┆ ---         ┆ ---         ┆ ---        │
│ str         ┆ i64         ┆ str    ┆ i64         ┆ str  ┆ str         ┆ str         ┆ str        │
╞═════════════╪═════════════╪════════╪═════════════╪══════╪═════════════╪═════════════╪════════════╡
│ MSFT-2024-i ┆ 4           ┆ MSFT   ┆ 2024        ┆ 7    ┆ What        ┆ Extended    ┆ Extended   │
│ tem7        ┆             ┆        ┆             ┆      ┆ potential   ┆ disruptions ┆ disruption │
│             ┆             ┆        ┆             ┆      ┆ supply      ┆ at certai…  ┆ s at these │
│             ┆             ┆        ┆             ┆      ┆ issue co…   ┆             ┆ …          │
│ NVDA-2024-i ┆ 6           ┆ NVDA   ┆ 2024        ┆ 1A   ┆ What new    ┆ NVIDIA DGX  ┆ We have    │
│ tem1A       ┆             ┆        ┆             ┆      ┆ cloud       ┆ Cloud       ┆ begun      │
│             ┆             ┆        ┆             ┆      ┆ service did ┆ services    ┆ offering   │
│             ┆             ┆        ┆             ┆      ┆ Nvi…        ┆             ┆ enterpr…   │
│ TSLA-2023-i ┆ 1           ┆ TSLA   ┆ 2023        ┆ 7    ┆ How many    ┆ Tesla       ┆ In 2023,   │
│ tem7        ┆             ┆        ┆             ┆      ┆ consumer    ┆ produced    ┆ we         │
│             ┆             ┆        ┆             ┆      ┆ vehicles    ┆ 1,845,985   ┆ produced   │
│             ┆             ┆        ┆             ┆      ┆ did…        ┆ consu…      ┆ 1,845,985… │
│ MSFT-2024-i ┆ 7           ┆ MSFT   ┆ 2024        ┆ 1A   ┆ What        ┆ Microsoft   ┆ Our focus  │
│ tem1A       ┆             ┆        ┆             ┆      ┆ execution   ┆ says its    ┆ on cloud-b │
│             ┆             ┆        ┆             ┆      ┆ and competi ┆ focus on    ┆ ased and   │
│             ┆             ┆        ┆             ┆      ┆ tive…       ┆ cl…         ┆ A…         │
│ NVDA-2024-i ┆ 45          ┆ NVDA   ┆ 2024        ┆ 15   ┆ What was    ┆ Nvidia's    ┆ weighted   │
│ tem15       ┆             ┆        ┆             ┆      ┆ the         ┆ operating   ┆ average    │
│             ┆             ┆        ┆             ┆      ┆ weighted    ┆ leases had  ┆ remaining  │
│             ┆             ┆        ┆             ┆      ┆ average …   ┆ …           ┆ lea…       │
│ …           ┆ …           ┆ …      ┆ …           ┆ …    ┆ …           ┆ …           ┆ …          │
│ MSFT-2024-i ┆ 10          ┆ MSFT   ┆ 2024        ┆ 1    ┆ What AI cyb ┆ Microsoft's ┆ Copilot    │
│ tem1        ┆             ┆        ┆             ┆      ┆ ersecurity  ┆ FY 2024 AI  ┆ for        │
│             ┆             ┆        ┆             ┆      ┆ product …   ┆ cyberse…    ┆ Security,  │
│             ┆             ┆        ┆             ┆      ┆             ┆             ┆ Microsof…  │
│ NVDA-2024-i ┆ 10          ┆ NVDA   ┆ 2024        ┆ 1    ┆ What new    ┆ CPUs        ┆ CPUs in    │
│ tem1        ┆             ┆        ┆             ┆      ┆ component   ┆             ┆ fiscal     │
│             ┆             ┆        ┆             ┆      ┆ did Nvidia  ┆             ┆ year 2024. │
│             ┆             ┆        ┆             ┆      ┆ …           ┆             ┆            │
│ TSLA-2025-i ┆ 3           ┆ TSLA   ┆ 2025        ┆ 9A   ┆ Did Tesla   ┆ No, there   ┆ There was  │
│ tem9A       ┆             ┆        ┆             ┆      ┆ report any  ┆ was no      ┆ no change  │
│             ┆             ┆        ┆             ┆      ┆ material …  ┆ change in   ┆ in our     │
│             ┆             ┆        ┆             ┆      ┆             ┆ our…        ┆ int…       │
│ MSFT-2025-i ┆ 5           ┆ MSFT   ┆ 2025        ┆ 1    ┆ What are    ┆ Microsoft   ┆ Build the  │
│ tem1        ┆             ┆        ┆             ┆      ┆ Microsoft’s ┆ aims to     ┆ intelligen │
│             ┆             ┆        ┆             ┆      ┆ primary i…  ┆ build an    ┆ t cloud    │
│             ┆             ┆        ┆             ┆      ┆             ┆ int…        ┆ an…        │
│ NVDA-2025-i ┆ 26          ┆ NVDA   ┆ 2025        ┆ 1    ┆ How does    ┆ Nvidia      ┆ Our        │
│ tem1        ┆             ┆        ┆             ┆      ┆ Nvidia      ┆ builds      ┆ developer  │
│             ┆             ┆        ┆             ┆      ┆ support and ┆ strong      ┆ program    │
│             ┆             ┆        ┆             ┆      ┆ en…         ┆ relations…  ┆ supports…  │
└─────────────┴─────────────┴────────┴─────────────┴──────┴─────────────┴─────────────┴────────────┘

In [24]:
questions_path = (
    Path(config.processed_data_dir) / instructions.output_file_name
)

In [25]:
print(questions_path)

/home/nasim/Desktop/work/rag/sec-10k-rag/data/processed/search_quality/questions.parquet

In [109]:
# write_to_parquet_file(questions, questions_path)

Writing facts to /home/nasim/Desktop/work/rag/sec-10k-rag/data/processed/search_quality/questions.parquet...
wrote 44 rows to /home/nasim/Desktop/work/rag/sec-10k-rag/data/processed/search_quality/questions.parquet in 0.02s

In [26]:
loaded_questions_df = load_parquet(questions_path)

In [27]:
print(loaded_questions_df.height)

44

In [35]:
questions_vector_df = get_question_vectors(questions_path)

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

In [36]:
display(questions_vector_df.head(10))

shape: (10, 11)
┌────────────┬────────────┬───────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ question_i ┆ section_id ┆ chunk_ind ┆ ticker ┆ … ┆ answer    ┆ quote     ┆ query     ┆ embedding │
│ d          ┆ ---        ┆ ex        ┆ ---    ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ ---        ┆ str        ┆ ---       ┆ str    ┆   ┆ str       ┆ str       ┆ str       ┆ array[f32 │
│ u32        ┆            ┆ i64       ┆        ┆   ┆           ┆           ┆           ┆ , 384]    │
╞════════════╪════════════╪═══════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0          ┆ MSFT-2024- ┆ 4         ┆ MSFT   ┆ … ┆ Extended  ┆ Extended  ┆ Represent ┆ [-0.00292 │
│            ┆ item7      ┆           ┆        ┆   ┆ disruptio ┆ disruptio ┆ this      ┆ 2,        │
│            ┆            ┆           ┆        ┆   ┆ ns at     ┆ ns at     ┆ sentence  ┆ 0.016542, │
│            ┆            ┆           ┆        ┆   ┆ certai…   ┆ these …   ┆ for se…   ┆ … 0.0260… │
│ 1          ┆ NVDA-2024- ┆ 6         ┆ NVDA   ┆ … ┆ NVIDIA    ┆ We have   ┆ Represent ┆ [-0.01895 │
│            ┆ item1A     ┆           ┆        ┆   ┆ DGX Cloud ┆ begun     ┆ this      ┆ 3, -0.054 │
│            ┆            ┆           ┆        ┆   ┆ services  ┆ offering  ┆ sentence  ┆ 395, …    │
│            ┆            ┆           ┆        ┆   ┆           ┆ enterpr…  ┆ for se…   ┆ 0.041…    │
│ 2          ┆ TSLA-2023- ┆ 1         ┆ TSLA   ┆ … ┆ Tesla     ┆ In 2023,  ┆ Represent ┆ [0.058794 │
│            ┆ item7      ┆           ┆        ┆   ┆ produced  ┆ we        ┆ this      ┆ , -0.0081 │
│            ┆            ┆           ┆        ┆   ┆ 1,845,985 ┆ produced  ┆ sentence  ┆ 97, …     │
│            ┆            ┆           ┆        ┆   ┆ consu…    ┆ 1,845,985 ┆ for se…   ┆ 0.0408…   │
│            ┆            ┆           ┆        ┆   ┆           ┆ …         ┆           ┆           │
│ 3          ┆ MSFT-2024- ┆ 7         ┆ MSFT   ┆ … ┆ Microsoft ┆ Our focus ┆ Represent ┆ [-0.00616 │
│            ┆ item1A     ┆           ┆        ┆   ┆ says its  ┆ on cloud- ┆ this      ┆ 8, -0.068 │
│            ┆            ┆           ┆        ┆   ┆ focus on  ┆ based and ┆ sentence  ┆ 961, …    │
│            ┆            ┆           ┆        ┆   ┆ cl…       ┆ A…        ┆ for se…   ┆ 0.009…    │
│ 4          ┆ NVDA-2024- ┆ 45        ┆ NVDA   ┆ … ┆ Nvidia's  ┆ weighted  ┆ Represent ┆ [0.017486 │
│            ┆ item15     ┆           ┆        ┆   ┆ operating ┆ average   ┆ this      ┆ , -0.0168 │
│            ┆            ┆           ┆        ┆   ┆ leases    ┆ remaining ┆ sentence  ┆ 45, …     │
│            ┆            ┆           ┆        ┆   ┆ had …     ┆ lea…      ┆ for se…   ┆ 0.0347…   │
│ 5          ┆ TSLA-2023- ┆ 14        ┆ TSLA   ┆ … ┆ Tesla     ┆ We face   ┆ Represent ┆ [0.012375 │
│            ┆ item1A     ┆           ┆        ┆   ┆ says it   ┆ strong    ┆ this      ┆ , -0.0173 │
│            ┆            ┆           ┆        ┆   ┆ faces     ┆ competiti ┆ sentence  ┆ 51, …     │
│            ┆            ┆           ┆        ┆   ┆ strong    ┆ on for…   ┆ for se…   ┆ 0.0201…   │
│            ┆            ┆           ┆        ┆   ┆ com…      ┆           ┆           ┆           │
│ 6          ┆ MSFT-2025- ┆ 30        ┆ MSFT   ┆ … ┆ Microsoft ┆ There are ┆ Represent ┆ [-0.04083 │
│            ┆ item1      ┆           ┆        ┆   ┆ has few   ┆ few       ┆ this      ┆ 5, -0.031 │
│            ┆            ┆           ┆        ┆   ┆ qualified ┆ qualified ┆ sentence  ┆ 272, …    │
│            ┆            ┆           ┆        ┆   ┆ su…       ┆ suppli…   ┆ for se…   ┆ 0.028…    │
│ 7          ┆ NVDA-2025- ┆ 51        ┆ NVDA   ┆ … ┆ 2007      ┆ Debora    ┆ Represent ┆ [-0.05766 │
│            ┆ item1      ┆           ┆        ┆   ┆           ┆ Shoquist  ┆ this      ┆ 1,        │
│            ┆            ┆           ┆        ┆   ┆           ┆ joined    ┆ sentence  ┆ 0.032401, │
│            ┆            ┆           ┆        ┆   ┆           ┆ NVIDIA …  ┆ for se…   ┆ … 0.0124… │
│ 8          ┆ TSLA-2023- ┆ 149       ┆ TSLA   ┆ … ┆ He        ┆ our CEO   ┆ Represent ┆ [-0.06812 │
│            ┆ item8      ┆           ┆        ┆   ┆ entered   ┆ entered   ┆ this      ┆ 2,        │
│            ┆            ┆           ┆        ┆   ┆ into an   ┆ into an   ┆ sentence  ┆ -0.00285, │
│            ┆            ┆           ┆        ┆   ┆ indemnifi ┆ indemn…   ┆ for se…   ┆ … 0.0346… │
│            ┆            ┆           ┆        ┆   ┆ ca…       ┆           ┆           ┆           │
│ 9          ┆ NVDA-2024- ┆ 40        ┆ NVDA   ┆ … ┆ There has ┆ no        ┆ Represent ┆ [0.071498 │
│            ┆ item7      ┆           ┆        ┆   ┆ been no   ┆ material  ┆ this      ┆ ,         │
│            ┆            ┆           ┆        ┆   ┆ material  ┆ impact to ┆ sentence  ┆ 0.043713, │
│            ┆            ┆           ┆        ┆   ┆ imp…      ┆ our resu… ┆ for se…   ┆ …         │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ -0.0026…  │
└────────────┴────────────┴───────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [39]:
pprint(config)

Config(command='run',
       root_dir=PosixPath('/home/nasim/Desktop/work/rag/sec-10k-rag'),
       input_data_dir=PosixPath('/home/nasim/Desktop/work/rag/sec-10k-rag/data/processed/search_quality'),
       processed_data_dir=PosixPath('/home/nasim/Desktop/work/rag/sec-10k-rag/data/processed/search_quality'),
       log_dir=PosixPath('/home/nasim/Desktop/work/rag/sec-10k-rag/logs'),
       temp_dir=PosixPath('/home/nasim/Desktop/work/rag/sec-10k-rag/temp'),
       instructions=GenerateQuestionsInstructions(db=DbConnInfo(port='5432',
                                                                dbname='sec10k',
                                                                user='rag',
                                                                host='127.0.0.1'),
                                                  llm_info=LlmInfo(model_name='openai/gpt-oss-120b',
                                                                   temperature=0.0),
                                                  sample_size=50,
                                                  seed=42,
                                                  output_file_name='questions.parquet',
                                                  chunks_table='chunks',
                                                  company_names={'MSFT': 'Microsoft',
                                                                 'NVDA': 'Nvidia',
                                                                 'TSLA': 'Tesla'}))

In [43]:
neighbors_df = find_nearest_neighbors(questions_vector_df, instructions.db, instructions.chunks_table, top_k=5)

In [47]:
with pl.Config(tbl_rows=-1): display(neighbors_df)

shape: (220, 4)
┌──────┬──────────────────┬─────────────┬─────────────┐
│ rank ┆ section_id       ┆ chunk_index ┆ question_id │
│ ---  ┆ ---              ┆ ---         ┆ ---         │
│ u32  ┆ str              ┆ i64         ┆ u32         │
╞══════╪══════════════════╪═════════════╪═════════════╡
│ 1    ┆ MSFT-2025-item1A ┆ 28          ┆ 0           │
│ 2    ┆ MSFT-2024-item1A ┆ 29          ┆ 0           │
│ 3    ┆ NVDA-2024-item1A ┆ 12          ┆ 0           │
│ 4    ┆ TSLA-2023-item1A ┆ 3           ┆ 0           │
│ 5    ┆ MSFT-2026-item1A ┆ 36          ┆ 0           │
│ 1    ┆ NVDA-2025-item1A ┆ 6           ┆ 1           │
│ 2    ┆ NVDA-2024-item1A ┆ 6           ┆ 1           │
│ 3    ┆ NVDA-2026-item1A ┆ 7           ┆ 1           │
│ 4    ┆ NVDA-2026-item1  ┆ 11          ┆ 1           │
│ 5    ┆ NVDA-2024-item7  ┆ 14          ┆ 1           │
│ 1    ┆ TSLA-2023-item7  ┆ 1           ┆ 2           │
│ 2    ┆ TSLA-2024-item7  ┆ 1           ┆ 2           │
│ 3    ┆ TSLA-2024-item7  ┆ 24          ┆ 2           │
│ 4    ┆ TSLA-2023-item8  ┆ 151         ┆ 2           │
│ 5    ┆ TSLA-2024-item8  ┆ 11          ┆ 2           │
│ 1    ┆ MSFT-2024-item1A ┆ 7           ┆ 3           │
│ 2    ┆ MSFT-2025-item1A ┆ 7           ┆ 3           │
│ 3    ┆ MSFT-2025-item7  ┆ 1           ┆ 3           │
│ 4    ┆ MSFT-2026-item7  ┆ 3           ┆ 3           │
│ 5    ┆ MSFT-2026-item1A ┆ 7           ┆ 3           │
│ 1    ┆ NVDA-2026-item15 ┆ 95          ┆ 4           │
│ 2    ┆ NVDA-2026-item15 ┆ 94          ┆ 4           │
│ 3    ┆ NVDA-2024-item15 ┆ 44          ┆ 4           │
│ 4    ┆ NVDA-2024-item15 ┆ 65          ┆ 4           │
│ 5    ┆ NVDA-2025-item15 ┆ 98          ┆ 4           │
│ 1    ┆ TSLA-2023-item1A ┆ 12          ┆ 5           │
│ 2    ┆ TSLA-2024-item1A ┆ 11          ┆ 5           │
│ 3    ┆ TSLA-2025-item7  ┆ 1           ┆ 5           │
│ 4    ┆ TSLA-2025-item1A ┆ 62          ┆ 5           │
│ 5    ┆ TSLA-2024-item7  ┆ 26          ┆ 5           │
│ 1    ┆ NVDA-2024-item1A ┆ 12          ┆ 6           │
│ 2    ┆ NVDA-2026-item1A ┆ 16          ┆ 6           │
│ 3    ┆ MSFT-2026-item1A ┆ 36          ┆ 6           │
│ 4    ┆ MSFT-2025-item1A ┆ 28          ┆ 6           │
│ 5    ┆ MSFT-2024-item1A ┆ 29          ┆ 6           │
│ 1    ┆ NVDA-2024-item1  ┆ 47          ┆ 7           │
│ 2    ┆ NVDA-2025-item1  ┆ 51          ┆ 7           │
│ 3    ┆ NVDA-2026-item1  ┆ 42          ┆ 7           │
│ 4    ┆ NVDA-2025-item1  ┆ 7           ┆ 7           │
│ 5    ┆ NVDA-2026-item1  ┆ 7           ┆ 7           │
│ 1    ┆ TSLA-2023-item8  ┆ 149         ┆ 8           │
│ 2    ┆ TSLA-2023-item15 ┆ 26          ┆ 8           │
│ 3    ┆ TSLA-2023-item8  ┆ 136         ┆ 8           │
│ 4    ┆ TSLA-2023-item16 ┆ 0           ┆ 8           │
│ 5    ┆ TSLA-2025-item16 ┆ 0           ┆ 8           │
│ 1    ┆ NVDA-2025-item1  ┆ 41          ┆ 9           │
│ 2    ┆ NVDA-2024-item1  ┆ 36          ┆ 9           │
│ 3    ┆ NVDA-2025-item1  ┆ 39          ┆ 9           │
│ 4    ┆ NVDA-2024-item1  ┆ 34          ┆ 9           │
│ 5    ┆ NVDA-2026-item1A ┆ 59          ┆ 9           │
│ 1    ┆ TSLA-2023-item8  ┆ 90          ┆ 10          │
│ 2    ┆ TSLA-2024-item8  ┆ 9           ┆ 10          │
│ 3    ┆ TSLA-2025-item8  ┆ 11          ┆ 10          │
│ 4    ┆ TSLA-2023-item8  ┆ 9           ┆ 10          │
│ 5    ┆ NVDA-2025-item15 ┆ 62          ┆ 10          │
│ 1    ┆ NVDA-2024-item15 ┆ 32          ┆ 11          │
│ 2    ┆ MSFT-2025-item8  ┆ 24          ┆ 11          │
│ 3    ┆ MSFT-2026-item8  ┆ 24          ┆ 11          │
│ 4    ┆ NVDA-2026-item15 ┆ 30          ┆ 11          │
│ 5    ┆ NVDA-2025-item15 ┆ 32          ┆ 11          │
│ 1    ┆ NVDA-2024-item1A ┆ 62          ┆ 12          │
│ 2    ┆ NVDA-2025-item7  ┆ 8           ┆ 12          │
│ 3    ┆ NVDA-2025-item1  ┆ 37          ┆ 12          │
│ 4    ┆ NVDA-2024-item7  ┆ 1           ┆ 12          │
│ 5    ┆ NVDA-2025-item7  ┆ 7           ┆ 12          │
│ 1    ┆ TSLA-2024-item7  ┆ 24          ┆ 13          │
│ 2    ┆ TSLA-2024-item7  ┆ 30          ┆ 13          │
│ 3    ┆ TSLA-2023-item1A ┆ 12          ┆ 13          │
│ 4    ┆ TSLA-2024-item1A ┆ 11          ┆ 13          │
│ 5    ┆ TSLA-2025-item7  ┆ 30          ┆ 13          │
│ 1    ┆ MSFT-2024-item1A ┆ 51          ┆ 14          │
│ 2    ┆ MSFT-2026-item1A ┆ 61          ┆ 14          │
│ 3    ┆ MSFT-2025-item1A ┆ 47          ┆ 14          │
│ 4    ┆ NVDA-2024-item1A ┆ 37          ┆ 14          │
│ 5    ┆ NVDA-2025-item1A ┆ 36          ┆ 14          │
│ 1    ┆ NVDA-2026-item15 ┆ 72          ┆ 15          │
│ 2    ┆ NVDA-2024-item15 ┆ 78          ┆ 15          │
│ 3    ┆ NVDA-2025-item15 ┆ 77          ┆ 15          │
│ 4    ┆ NVDA-2024-item15 ┆ 76          ┆ 15          │
│ 5    ┆ NVDA-2025-item15 ┆ 75          ┆ 15          │
│ 1    ┆ TSLA-2025-item8  ┆ 47          ┆ 16          │
│ 2    ┆ TSLA-2024-item8  ┆ 9           ┆ 16          │
│ 3    ┆ TSLA-2023-item8  ┆ 9           ┆ 16          │
│ 4    ┆ TSLA-2025-item8  ┆ 11          ┆ 16          │
│ 5    ┆ TSLA-2023-item8  ┆ 122         ┆ 16          │
│ 1    ┆ MSFT-2025-item8  ┆ 64          ┆ 17          │
│ 2    ┆ TSLA-2024-item8  ┆ 114         ┆ 17          │
│ 3    ┆ NVDA-2025-item15 ┆ 84          ┆ 17          │
│ 4    ┆ MSFT-2024-item8  ┆ 66          ┆ 17          │
│ 5    ┆ MSFT-2026-item8  ┆ 64          ┆ 17          │
│ 1    ┆ NVDA-2024-item15 ┆ 68          ┆ 18          │
│ 2    ┆ NVDA-2024-item15 ┆ 94          ┆ 18          │
│ 3    ┆ NVDA-2025-item15 ┆ 92          ┆ 18          │
│ 4    ┆ NVDA-2026-item15 ┆ 92          ┆ 18          │
│ 5    ┆ NVDA-2026-item15 ┆ 89          ┆ 18          │
│ 1    ┆ TSLA-2023-item8  ┆ 71          ┆ 19          │
│ 2    ┆ TSLA-2024-item1  ┆ 21          ┆ 19          │
│ 3    ┆ TSLA-2024-item8  ┆ 68          ┆ 19          │
│ 4    ┆ TSLA-2023-item1  ┆ 19          ┆ 19          │
│ 5    ┆ TSLA-2025-item8  ┆ 75          ┆ 19          │
│ 1    ┆ MSFT-2024-item10 ┆ 1           ┆ 20          │
│ 2    ┆ MSFT-2026-item15 ┆ 11          ┆ 20          │
│ 3    ┆ MSFT-2025-item15 ┆ 11          ┆ 20          │
│ 4    ┆ MSFT-2024-item10 ┆ 2           ┆ 20          │
│ 5    ┆ MSFT-2025-item15 ┆ 9           ┆ 20          │
│ 1    ┆ TSLA-2023-item15 ┆ 23          ┆ 21          │
│ 2    ┆ TSLA-2024-item15 ┆ 21          ┆ 21          │
│ 3    ┆ TSLA-2023-item15 ┆ 24          ┆ 21          │
│ 4    ┆ TSLA-2023-item15 ┆ 22          ┆ 21          │
│ 5    ┆ TSLA-2023-item15 ┆ 25          ┆ 21          │
│ 1    ┆ MSFT-2024-item1  ┆ 65          ┆ 22          │
│ 2    ┆ MSFT-2026-item1  ┆ 39          ┆ 22          │
│ 3    ┆ MSFT-2025-item1  ┆ 46          ┆ 22          │
│ 4    ┆ MSFT-2024-item1  ┆ 63          ┆ 22          │
│ 5    ┆ MSFT-2025-item1  ┆ 44          ┆ 22          │
│ 1    ┆ NVDA-2024-item15 ┆ 96          ┆ 23          │
│ 2    ┆ NVDA-2024-item15 ┆ 73          ┆ 23          │
│ 3    ┆ NVDA-2024-item15 ┆ 14          ┆ 23          │
│ 4    ┆ NVDA-2024-item15 ┆ 65          ┆ 23          │
│ 5    ┆ NVDA-2024-item15 ┆ 63          ┆ 23          │
│ 1    ┆ TSLA-2024-item15 ┆ 16          ┆ 24          │
│ 2    ┆ TSLA-2023-item15 ┆ 9           ┆ 24          │
│ 3    ┆ TSLA-2023-item15 ┆ 16          ┆ 24          │
│ 4    ┆ TSLA-2024-item15 ┆ 9           ┆ 24          │
│ 5    ┆ TSLA-2024-item15 ┆ 13          ┆ 24          │
│ 1    ┆ MSFT-2024-item10 ┆ 2           ┆ 25          │
│ 2    ┆ MSFT-2024-item10 ┆ 1           ┆ 25          │
│ 3    ┆ MSFT-2024-item1  ┆ 61          ┆ 25          │
│ 4    ┆ MSFT-2025-item1  ┆ 42          ┆ 25          │
│ 5    ┆ MSFT-2026-item15 ┆ 11          ┆ 25          │
│ 1    ┆ NVDA-2026-item15 ┆ 17          ┆ 26          │
│ 2    ┆ NVDA-2024-item15 ┆ 68          ┆ 26          │
│ 3    ┆ NVDA-2024-item15 ┆ 73          ┆ 26          │
│ 4    ┆ NVDA-2025-item15 ┆ 72          ┆ 26          │
│ 5    ┆ NVDA-2024-item15 ┆ 96          ┆ 26          │
│ 1    ┆ TSLA-2023-item15 ┆ 23          ┆ 27          │
│ 2    ┆ TSLA-2024-item15 ┆ 21          ┆ 27          │
│ 3    ┆ TSLA-2023-item15 ┆ 22          ┆ 27          │
│ 4    ┆ TSLA-2024-item1A ┆ 26          ┆ 27          │
│ 5    ┆ TSLA-2023-item1A ┆ 26          ┆ 27          │
│ 1    ┆ NVDA-2025-item7  ┆ 11          ┆ 28          │
│ 2    ┆ MSFT-2025-item7  ┆ 13          ┆ 28          │
│ 3    ┆ NVDA-2024-item7  ┆ 10          ┆ 28          │
│ 4    ┆ MSFT-2024-item7  ┆ 14          ┆ 28          │
│ 5    ┆ MSFT-2025-item7  ┆ 1           ┆ 28          │
│ 1    ┆ NVDA-2025-item7  ┆ 1           ┆ 29          │
│ 2    ┆ NVDA-2026-item15 ┆ 92          ┆ 29          │
│ 3    ┆ NVDA-2025-item15 ┆ 8           ┆ 29          │
│ 4    ┆ NVDA-2025-item15 ┆ 94          ┆ 29          │
│ 5    ┆ NVDA-2026-item15 ┆ 89          ┆ 29          │
│ 1    ┆ TSLA-2024-item7  ┆ 26          ┆ 30          │
│ 2    ┆ TSLA-2024-item7  ┆ 1           ┆ 30          │
│ 3    ┆ TSLA-2024-item7  ┆ 2           ┆ 30          │
│ 4    ┆ TSLA-2025-item7  ┆ 1           ┆ 30          │
│ 5    ┆ TSLA-2024-item7  ┆ 10          ┆ 30          │
│ 1    ┆ NVDA-2025-item1A ┆ 22          ┆ 31          │
│ 2    ┆ NVDA-2026-item15 ┆ 68          ┆ 31          │
│ 3    ┆ NVDA-2026-item1A ┆ 25          ┆ 31          │
│ 4    ┆ NVDA-2024-item7  ┆ 1           ┆ 31          │
│ 5    ┆ NVDA-2026-item7  ┆ 0           ┆ 31          │
│ 1    ┆ TSLA-2023-item15 ┆ 32          ┆ 32          │
│ 2    ┆ TSLA-2025-item15 ┆ 6           ┆ 32          │
│ 3    ┆ TSLA-2025-item9B ┆ 0           ┆ 32          │
│ 4    ┆ TSLA-2025-item8  ┆ 149         ┆ 32          │
│ 5    ┆ TSLA-2024-item16 ┆ 0           ┆ 32          │
│ 1    ┆ MSFT-2025-item1A ┆ 27          ┆ 33          │
│ 2    ┆ MSFT-2024-item1A ┆ 28          ┆ 33          │
│ 3    ┆ MSFT-2026-item1A ┆ 38          ┆ 33          │
│ 4    ┆ MSFT-2026-item1A ┆ 32          ┆ 33          │
│ 5    ┆ MSFT-2024-item7  ┆ 23          ┆ 33          │
│ 1    ┆ NVDA-2025-item15 ┆ 72          ┆ 34          │
│ 2    ┆ NVDA-2025-item15 ┆ 11          ┆ 34          │
│ 3    ┆ NVDA-2024-item15 ┆ 11          ┆ 34          │
│ 4    ┆ NVDA-2024-item15 ┆ 8           ┆ 34          │
│ 5    ┆ NVDA-2026-item15 ┆ 17          ┆ 34          │
│ 1    ┆ NVDA-2024-item15 ┆ 68          ┆ 35          │
│ 2    ┆ NVDA-2024-item7  ┆ 1           ┆ 35          │
│ 3    ┆ NVDA-2024-item1  ┆ 36          ┆ 35          │
│ 4    ┆ NVDA-2025-item1  ┆ 41          ┆ 35          │
│ 5    ┆ NVDA-2026-item15 ┆ 62          ┆ 35          │
│ 1    ┆ TSLA-2023-item8  ┆ 130         ┆ 36          │
│ 2    ┆ TSLA-2024-item1A ┆ 26          ┆ 36          │
│ 3    ┆ TSLA-2023-item1A ┆ 26          ┆ 36          │
│ 4    ┆ TSLA-2023-item8  ┆ 129         ┆ 36          │
│ 5    ┆ TSLA-2024-item8  ┆ 119         ┆ 36          │
│ 1    ┆ MSFT-2025-item7  ┆ 36          ┆ 37          │
│ 2    ┆ NVDA-2026-item7  ┆ 16          ┆ 37          │
│ 3    ┆ MSFT-2024-item7  ┆ 40          ┆ 37          │
│ 4    ┆ NVDA-2025-item7  ┆ 20          ┆ 37          │
│ 5    ┆ MSFT-2026-item7  ┆ 39          ┆ 37          │
│ 1    ┆ TSLA-2025-item7  ┆ 1           ┆ 38          │
│ 2    ┆ TSLA-2025-item1A ┆ 16          ┆ 38          │
│ 3    ┆ TSLA-2023-item7  ┆ 5           ┆ 38          │
│ 4    ┆ TSLA-2025-item1A ┆ 11          ┆ 38          │
│ 5    ┆ TSLA-2024-item7  ┆ 6           ┆ 38          │
│ 1    ┆ MSFT-2026-item1C ┆ 0           ┆ 39          │
│ 2    ┆ MSFT-2024-item1  ┆ 10          ┆ 39          │
│ 3    ┆ MSFT-2024-item1  ┆ 49          ┆ 39          │
│ 4    ┆ MSFT-2026-item1  ┆ 18          ┆ 39          │
│ 5    ┆ MSFT-2024-item1  ┆ 8           ┆ 39          │
│ 1    ┆ NVDA-2026-item1  ┆ 8           ┆ 40          │
│ 2    ┆ NVDA-2024-item1  ┆ 10          ┆ 40          │
│ 3    ┆ NVDA-2024-item7  ┆ 1           ┆ 40          │
│ 4    ┆ NVDA-2024-item7  ┆ 14          ┆ 40          │
│ 5    ┆ NVDA-2024-item7  ┆ 12          ┆ 40          │
│ 1    ┆ TSLA-2025-item8  ┆ 0           ┆ 41          │
│ 2    ┆ TSLA-2023-item8  ┆ 0           ┆ 41          │
│ 3    ┆ TSLA-2024-item8  ┆ 0           ┆ 41          │
│ 4    ┆ NVDA-2025-item9A ┆ 1           ┆ 41          │
│ 5    ┆ NVDA-2024-item9A ┆ 1           ┆ 41          │
│ 1    ┆ MSFT-2025-item7  ┆ 1           ┆ 42          │
│ 2    ┆ NVDA-2025-item7  ┆ 11          ┆ 42          │
│ 3    ┆ MSFT-2024-item1  ┆ 13          ┆ 42          │
│ 4    ┆ MSFT-2024-item7  ┆ 14          ┆ 42          │
│ 5    ┆ MSFT-2026-item1  ┆ 7           ┆ 42          │
│ 1    ┆ NVDA-2025-item7  ┆ 1           ┆ 43          │
│ 2    ┆ NVDA-2024-item7  ┆ 14          ┆ 43          │
│ 3    ┆ NVDA-2024-item7  ┆ 1           ┆ 43          │
│ 4    ┆ NVDA-2026-item1  ┆ 2           ┆ 43          │
│ 5    ┆ NVDA-2024-item1  ┆ 2           ┆ 43          │
└──────┴──────────────────┴─────────────┴─────────────┘